### ISSUE TITLE
Tags after 1.2.2 not PHP 7.3 compatible

### ISSUE THREAD

**Issue by sparks34** [QualityUnit/TNEFDecoder#20]
Hello,

my project is currently running on PHP 7.3. On packagist, it is said that you the bundle is compatible with PHP 7.0 and newer but the new added class TNEFBuffer on tag 1.2.3 has typed fields which are only compatible with PHP 7.4. 

Can you fix that please ? Or specify on packagist that starting on tag 1.2.3, the bundle is only compatible with PHP 7.4. 

Thanks.

**Comment by jperdochqu** [comment]
@sparks34 thx for notice. Should be fixed by https://github.com/QualityUnit/TNEFDecoder/pull/21 and released in version 1.2.8.
