### ISSUE TITLE
Files ".dat" not supported with signature 0x7261762f

### ISSUE THREAD

**Issue by SantiFeng** [QualityUnit/TNEFDecoder#24]
Some .dat files are not supported by the library. I was able to parse the file with tnef in the terminal, but not with the library installed.

Enviroment:
-PHP 8.2 tested.
-PHP 7.4 tested.
-MBString ext enabled.

![image](https://github.com/QualityUnit/TNEFDecoder/assets/154356724/4832cb35-1d8c-4c20-bd87-af2127320b65)

Signature: 0x7261762f seems to be failing.

**Comment by jperdochqu** [comment]
This is not "some .dat file decoder", but it's TNEF decoder. According to specification (and example https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxtnef/7fdb64ee-7f63-4d95-9af1-c672e7475c3a) signature must be `0x223e9f78`, it's constant. So it seems as not valid TNEF file. Anyway, it's not possible to analyse without example.
