### ISSUE TITLE
Get HTML body

### ISSUE THREAD

**Issue by shmshd** [QualityUnit/TNEFDecoder#7]
Is there an object to get HTML body from winmail.dat file?

**Comment by martincivan** [comment]
@shmshd 
As far as I know there is no way to get HTML or plain-text message body yet. Only RTF file is extracted if it was included in the file.
We know about this flaw and we would like to add this feature in the future but at this time it does not have a guaranteed place in our road-map.

We would be happy to accept any contribution, if you would like to contribute. For example, it might be possible to include the function from https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_tnef_decoder.php

**Comment by maestorr** [comment]
I was able to grab the HTML, but for testing purposes I need more winmail.dat files to test. If that works in those files as well, I can do a pull request. At this moment I only have one winmail.dat file. Could you show me a path to get sample winmail files?

**Comment by shmshd** [comment]
I was able to get the HTML, but to verify and improve I need more winmail.dat files. If that works I can do a PR. At this moment I only have one winmail.dat file. Could you show me paths to get the sample winmail files?

**Comment by martincivan** [comment]
In tests folder [link](https://github.com/QualityUnit/TNEFDecoder/tree/master/tests/testfiles) there is a directory with some test tnef files, that we used in our attachment tests.
 Have you checked those? I am not sure whether they contain also HTML though.

**Comment by shmshd** [comment]
I've added a PR #8

**Comment by martincivan** [comment]
@shmshd Thank you for your PR, however I do not think that it is optimal to search for opening and closing tag in the raw data. I tried to do it using the TNEF flags and it seems to work fine with ours test files.
 Could you please check https://github.com/QualityUnit/TNEFDecoder/pull/9/ with your test file? (function `getBodyElements` in TNEFAttachment)

**Comment by shmshd** [comment]
@martincivan I guess that the only way to find the HTML body of the TNEF file. The test was first done with my test file (original `winmail.dat` file) and then I tested your TNEF files with HTML such as `MAPI_ATTACH_DATA_OBJ.tnef`, `unicode-mapi-attr.tnef` & `unicode-mapi-attr-name.tnef`. Though I'm not sure if other files contain any HTML body. 

Btw I didn't get the `getBodyElements` part.

**Comment by martincivan** [comment]
@shmshd Sorry, if my message was not clear.
I mean, I created a pull request #9 (branch `i8` it this repo) with added logic to extract body part of TNEF file using TNEF flags (or pages or whatever is it called). 
I tested it with our test files and it successfully extracted HTML body from files unicode-mapi-attr.tnef & unicode-mapi-attr-name.tnef

And I would like to ask you, if you could test it also using your TNEF file, before I merge it.

**Comment by shmshd** [comment]
oops. I was late. I removed my message when I understood, but I was too late.

ok, let me do a test

**Comment by shmshd** [comment]
Hi, the test was successful. HTML was returned for my test file. But, when I checked with your test files which contain HTML, your `MAPI_ATTACH_DATA_OBJ.tnef` returned empty array.

**Comment by martincivan** [comment]
I noticed it too, but I guess that the HTML comes from an attachment VIA_Nytt_14021.htm , but unfortunately, it is empty. I guess that this file is malformed in some way, but I think that this solution in should work fine in general.

Anyway, I am going to merge and release this.

**Comment by shmshd** [comment]
okay cool

**Comment by shmshd** [comment]
> I noticed it too, but I guess that the HTML comes from an attachment VIA_Nytt_14021.htm , but unfortunately, it is empty. I guess that this file is malformed in some way, but I think that this solution in should work fine in general.
> 
> Anyway, I am going to merge and release this.

Btw, just now I did a test with my closed PR #8 and I was able to get the HTML for `TAPI_ATTACH_DATA_OBJ.tnef`. [HTML was not empty](https://pastebin.com/raw/Jmd2L2sm).

**Comment by martincivan** [comment]
The HTML comes from email attachment - it is not message body.
I am not sure why those attachment files are decoded as empty (it may be broken file or a bug in the decoder), but since this is the only example, I close this.
